name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        VIPS_VERSION: ["8.10.0"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: apk
        run: sudo apt-get update && sudo apt-get install -y git build-essential automake libtool swig libxml2-dev libfftw3-dev \
          libmagickwand-dev libopenexr-dev liborc-0.4-0 gobject-introspection \
          libgsf-1-dev libglib2.0-dev liborc-0.4-dev gtk-doc-tools libopenslide-dev \
          libmatio-dev libgif-dev libwebp-dev libjpeg-turbo8-dev libexpat1-dev \
          libexif-dev libtiff5-dev libcfitsio-dev libpoppler-glib-dev librsvg2-dev libpango1.0-dev \
          libffi-dev libopenjp2-7-dev libimagequant-dev libcgif-dev libgirepository1.0-dev
      - name: get vips
        run: wget https://github.com/libvips/libvips/releases/download/v${VIPS_VERSION}/vips-${VIPS_VERSION}.tar.gz
      - name: untar
        run: mkdir vips && tar xvzf vips-${VIPS_VERSION}.tar.gz -C vips --strip-components 1
      - name: make & install
        run: cd vips && make && sudo make install && ldconfig /etc/ld.so.conf.d
      - name: cleanup
        run: rm -rf vips vips-${VIPS_VERSION}.tar.gz
      - name: rustup
        run: rustup component add rustfmt --toolchain 1.45.2-x86_64-unknown-linux-musl
      - name: generate
        run: cargo build
